url: "https://sekika.github.io/kaidoku/"
title: Kaidoku
description: Player, solver and creater of sudoku puzzles
show_downloads: false
google_analytics:
theme: jekyll-theme-merlot
version: 0.3.0
jquery-version: "3.2.1" # jQuery https://jquery.com/download/
