url: "https://sekika.github.io/kaidoku/"
title: Kaidoku
description: Player, solver and creater of sudoku puzzles
show_downloads: true
google_analytics:
theme: jekyll-theme-merlot
version: 0.5.2
jquery-version: "3.2.1" # jQuery https://jquery.com/download/
problems: 25000
